ALTER TABLE "Assignment"
ADD COLUMN "maxPoints" DOUBLE PRECISION;

ALTER TABLE "HomeworkSubmission"
ADD COLUMN "reviewedAt" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
